require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'kidzlim_cli' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'OpenSSL-Universal'

  pod 'RNInputMask', :path => '../node_modules/react-native-text-input-mask/ios/InputMask'
  pod 'react-native-text-input-mask', :path => '../node_modules/react-native-text-input-mask'

# add pods for desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

pod 'Firebase/Auth'
pod 'Firebase/Messaging'
pod 'Firebase/InAppMessaging'

pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  post_install do |installer|
    # flipper_post_install(installer)
  end
end
